### ISSUE TITLE
Missing amla

### ISSUE THREAD

**Issue by ProditorMagnus** [windfolk/Era_of_Chaos#3]
https://github.com/windfolk/Era_of_Chaos/blob/master/units/human-chaos/Chaos_Sharpshooter.cfg

**Comment by ProditorMagnus** [comment]
Same for https://github.com/windfolk/Era_of_Chaos/blob/master/units/elementals/Lava_Ettin.cfg

**Comment by bumbadadabum** [comment]
Thanks I fixed this.
